# Generated by Django 5.0.6 on 2024-06-27 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='img2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='img3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='img4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project/'),
            preserve_default=False,
        ),
    ]
