# Generated by Django 5.0.6 on 2024-06-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_project_img1_project_img2_project_img3_project_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
